### ISSUE TITLE
Standardize Dapps guides for Truffle, Hardhat & Foundry

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/avalanche-docs#1059]
The guides of the dev toolchains [Truffle](https://docs.avax.network/dapps/smart-contracts/using-truffle-with-the-avalanche-c-chain), [Hardhat](https://docs.avax.network/dapps/smart-contracts/using-hardhat-with-the-avalanche-c-chain) and [Foundry](https://docs.avax.network/dapps/smart-contracts/using-foundry-with-the-avalanche-c-chain) are structured very differently, which makes it hard to compare the different tools and choose the appropriate setup. 

- The guides use different wordings for their headings (Prerequisites vs. Requirements vs. Dependencies) and they appear in different orders
- The Hardhat guide starts with a general introduction to Avalanche, which I think can be removed 
- The Foundry guide is not linked on the [Smart Contract Overview](https://docs.avax.network/dapps/smart-contracts)

I will submit a pull request with a standardized format for the guides

**Comment by martineckardt** [comment]
Let me know if that goes in the right direction. Happy to keep working the guides to make them even better

**Comment by ashucoder9** [comment]
Thank you for the contribution @martineckardt

I hope you'll enjoy opening more PRs as a maintainer now!
