### ISSUE TITLE
Ledger live integration in non-experimental mode

### ISSUE THREAD

**Issue by whittin3** [ava-labs/avalanche-docs#118]
I see that there is a guide to [set up a Ledger Nano S/X  with Avalanche](https://docs.avax.network/build/tutorials/platform/setup-your-ledger-nano-s-with-avalanche#135b). However in the guide it states:
`The Avalanche Ledger wallet app is currently available via Ledger Live in Experimental Mode.`

Why is this? Is enabling Avalanche to work with ledger in the standard mode (non-expiremntal mode) a feature request I should be requesting from Ledger or here? 

Thank you!

**Comment by whittin3** [comment]
Ah I see the app is maintained by Ava-Labs here https://github.com/ava-labs/ledger-app-avalanche . Is there a roadmap or any information you can share around when one might expect this feature request to be available?

**Comment by danlaine** [comment]
Before an app is listed on Ledger Live, it is listed in "experimental" mode.
We are working with the Ledger team to have the Avalanche app listed as a regular application (i.e. not in experimental mode.)
Unfortunately we don't have an exact timeline for when this will happen.

**Comment by whittin3** [comment]
Thanks so much for the quick response. Will subscribe for updates.
