### ISSUE TITLE
Establish Results Based KPIs for Documentation

### ISSUE THREAD

**Issue by aaronbuchwald** [ava-labs/avalanche-docs#1207]
# Results Based KPIs

We should start tracking the resulting quality of our documentation. As a first pass, we should try out the following metrics:

- Total documentation page views
- Support: what percentage of incoming questions can we answer by pointing to a specific piece of documentation?
- Assign a rating out of 5 stars to each piece of documentation
- Calculate average rating per documentation page view (prioritize improving pages with the most views)

These are not intended to be permanent, but to start tracking our documentation process better, so that we can continue to iterate and improve.

# Tickets

- [ ] Ingest Google Analytics on total page views into dashboard
- [ ] Create way for support team to track how frequently they are/are not able to point to a specific piece of documentation to answer incoming questions
- [ ] Internal audit to assign rating to each documentation page
- [ ] Ingest average rating per documentation page view into dashboard
- [ ] Add poll to documentation pages to ask users for a rating

**Comment by ashucoder9** [comment]
I believe the Analytics are in place @Andyvargtz and implementing a rating system for docs pages is the remaining part. Rest is being handled by the DevRel team's documentation upgrade efforts.

Shall we close this issue and create a new one for implementing a rating system into docs?

**Comment by laviniat1996** [comment]
@ashucoder9 The rating would come from users, as feedback?

**Comment by ashucoder9** [comment]
> @ashucoder9 The rating would come from users, as feedback?

Yes. We can look into adding an upvote/downvote button.

**Comment by laviniat1996** [comment]
@ashucoder9  I can take this up.

**Comment by ashucoder9** [comment]
For sure, lmk if you need any help. I can suggest a few implementation ideas.

**Comment by laviniat1996** [comment]
@ashucoder9 This is super late, but do we have a backend already where we store dev docs data?

**Comment by laviniat1996** [comment]
@aaronbuchwald  Added feedback to docs
