### ISSUE TITLE
Breaking change for unattended installation

### ISSUE THREAD

**Issue by cryptoklings** [ava-labs/avalanche-docs#1299]
The changes introduced in #1208 breaks [unattended installation](https://docs.avax.network/nodes/build/set-up-node-with-installer#unattended-installation) when remote RPC is required. 

I have the RPC port open to specific ips for two purposes:
* Health checks from an external machine (RPC health endpoint)
* Grafana agent running on external machine (metrics endpoint)

After switching to the new argument: `--rpc public` the script will still prompt:

```
Are you sure you want to allow public access to the RPC port? [yes, no]:
```

AFAIK there's no way around this, so this breaks unattended installation. Please enlighten me if I've missed something here.

I'm all for warning (new) users about the dangers of leaving the RPC endpoint open to the world, but I'm also for unattended installs so perhaps the following would be a reasonable tradeoff:

* If `--rpc` is not given as an argument, the user is interactively working through the script. No problem in giving them the extra warning in that case.
* If the `--rpc public` argument is given, assume that it's an unattended install. Perhaps write a warning, but don't block script execution.

**Comment by meaghanfitzgerald** [comment]
@jpop32 Please lmk if this issue still needs to be addressed or if it can be closed.

**Comment by jpop32** [comment]
It's true, this borks the unattended installation. I'll look into fixing it.

**Comment by jpop32** [comment]
Addressed in [this PR](https://github.com/ava-labs/avalanche-docs/pull/1582).
