### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/avalanche-docs#1383]
### Current Behavior

The documentation website currently includes a dropdown to select language but our only supported language is English. This is causing confusion for users and preventing us from supporting devs from our target markets/regions. 

### Expected Behavior

We need to add a service that translates our documentation into other languages. This will improve the user experience and ensure that the documentation is clear and reached a wider developer audience. 

### Steps to Reproduce

Visit the documentation website.
Observe the presence of the language selection dropdown in the navbar.

### Proposed Solution

Implement a service to translate our documents into Chinese, Korean, and Spanish. In the future we should add even more languages. Get started in the docusaurus documentation here: https://docusaurus.io/docs/i18n/introduction. 

Alternative: We've been working on a solution to translate support and dev docs into Korean and Japanese. Here is the proposal and cost to translate the entire dev docs to Korean and Japanese.

Crowdin:

-requires manual hiring of translators
-also had issues w/past translations due to crypto-specific terms
-Requires more hands-on updates for each sync/update, including a PR for each update on Dev docs

Smartling:
-No PRs required to update dev docs, just sync the site using their dashboard to have it begin any translation updates
-They provide all the translators, and no extra steps in hiring are needed
-Base platform costs and annual costs higher

We can bring over the translated library from Crowdin to Smartling also to help reduce the costs as some words are already translated from Core ext/mobile project.

**Comment by yulin-dong** [comment]
See previous attempt: https://github.com/ava-labs/avalanche-docs/pull/512

**Comment by meaghanfitzgerald** [comment]
@yulin-dong did this PR result in a full chinese translation? Why can't we see it now?

**Comment by yulin-dong** [comment]
> @yulin-dong did this PR result in a full chinese translation? Why can't we see it now?

No, it was just a prototype to go through the process of i18n by docusaurus with Crowdin. You can see the preview link at  https://3bd07002.avalanche-docs.pages.dev/zh-cn/

**Comment by Wholesomebruh** [comment]
@meaghanfitzgerald Will it be ok, if a whole new site is created with translated content, like vue js or vite js documentation?

**Comment by meaghanfitzgerald** [comment]
@Wholesomebruh Ideally it would be implemented within our own documentation site, similar to how [webdriver.io](https://webdriver.io/) has done it.

**Comment by Wholesomebruh** [comment]
@meaghanfitzgerald Please assign it to me, I'm working on it.

**Comment by meaghanfitzgerald** [comment]
@Wholesomebruh any updates on this? any issues I can help with?

**Comment by Wholesomebruh** [comment]
Thanks for asking, I manually translated the docs, which can later be synced with smartlings. Currently , I am implementing i18n from docusaurus itself which will be free of cost , facing some issues with broken link. Will raise a PR , once I'm done debugging.

**Comment by meaghanfitzgerald** [comment]
@Wholesomebruh any more updates? i18n would be a big improvement

**Comment by anuragasawa20** [comment]
Hello so I would like to contribute in it for multiple languages using i18n and I have experience in it I implemented this type of localization for push protocol (https://push.org/) and got bounty. so can we discuss on it

**Comment by anuragasawa20** [comment]
yeah I have done for their home Page so I can do it for both our home page and Docs using i18n
