### ISSUE TITLE
Further document chain behavior

### ISSUE THREAD

**Issue by exdx** [ava-labs/avalanche-docs#1393]
The following can be expanded upon in our docs per @StephenButtolph 
```
* What happens when you --track-subnets.
* How to access APIs for the blockchains that are spun up
* How to alias the default API endpoints for better URL readability
```
It's also worth mentioning that in the case of aliasing, the alias is set on a per-node basis. Therefore in a multi-node cluster to set an alias across the cluster you would need to update every node (via the admin API or the node config) in order to use the alias across the network. Basically there is no gossiping of the alias or reconciliation across nodes. 

cc @meaghanfitzgerald

**Comment by exdx** [comment]
Notes on point 3 the admin API

* I think the [existing admin API page](https://docs.avax.network/apis/avalanchego/apis/admin) does a good job explaining the admin API methods and how they work. It's worth adding the following as an info blurb imo (this is what surprised me when working with the admin API). 

Aliasing a chain can be done through the `/ext/admin` API or the [node configuration `--chain-aliases-file` flag](https://docs.avax.network/nodes/maintain/avalanchego-config-flags#--chain-aliases-file-string). Note that the alias is set for each chain on each node individually. In a multi-node subnet, the same alias should be configured on each node to use an alias across the subnet successfully. Setting an alias for a chain on one node does not register that alias with other nodes automatically.

**Comment by meaghanfitzgerald** [comment]
@exdx Will you please raise a PR with the proposed changes? The PR template will guide you through how best to avoid the build failing because of linting issues

**Comment by exdx** [comment]
#1417
