### ISSUE TITLE
Consistent landing page on each section

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/avalanche-docs#1395]
There are different landing pages on each section.

On Learn: it is https://docs.avax.network/intro
On Quickstart: it is https://docs.avax.network/quickstart
On Subnet: it is https://docs.avax.network/subnets/when-to-use-subnet-vs-c-chain

We should be consistent on the landing pages. I would propose to add a README in each section as in https://docs.avax.network/quickstart

**Comment by meaghanfitzgerald** [comment]
@laviniat1996 we should sync on this, I was planning to remove the Quickstart tab as part of the docs revamp all together, among other upgrades. Consistent landing pages should be added to other tabs but the layout of our docs is going to change drastically so it might be counter-product to do so now

**Comment by meaghanfitzgerald** [comment]
I am planning to make a diagram this week of the current state of our docs and the desired future state so that everyone can reference.
