### ISSUE TITLE
Typos in the Hello World Precompile Tutorial

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche-docs#1428]
## Bug Description

While working through the [Hello World Precompile Tutorial](https://docs.avax.network/subnets/hello-world-precompile-tutorial) I ran into several bugs. They're mostly typos or path issues. Below is a list of issues to be fixed.

## List of Bugs

1. Path issue. The docs say `./contract-examples/contracts/` but the actual path is `./contracts/contracts/`.
2. Undefined variables in `contract.go`. `storageKeyHash` and `ErrInputExceedsLimit`.
3. Typo on function name. `contract.deductGas` should be `contract.DeductGas`.
4. Typo in tests. `utils.ExecuteHardHatTestOnNewBlockchain` should be `utils.RunDefaultHardhatTests`.
5. Need to install the npm packages which isn’t in the docs.
6. Confirm that you're running the most recent version of ANR .

**Comment by meaghanfitzgerald** [comment]
Is this still an issue in the docs or has it been resolved: @ceyonur @cgcardona
