### ISSUE TITLE
--http-allowed-hosts AvalancheGo flag is not documented

### ISSUE THREAD

**Issue by leopaul36** [ava-labs/avalanche-docs#1434]
**Is your feature request related to a problem? Please describe.**
The `--http-allowed-hosts` AvalancheGo flag introduced in https://github.com/ava-labs/avalanchego/releases/tag/v1.10.3 is not documented in the [AvalancheGo Config and Flags](https://docs.avax.network/nodes/maintain/avalanchego-config-flags).

**Comment by meaghanfitzgerald** [comment]
Acknowledged, thanks for raising this.

**Comment by hexfusion** [comment]
@leopaul36 would you be interested raising a PR to resolve this :pray: ?

ref. https://github.com/ava-labs/avalanche-docs/blob/master/docs/nodes/maintain/avalanchego-config-flags.md

**Comment by leopaul36** [comment]
> @leopaul36 would you be interested raising a PR to resolve this pray ?
> 
> ref. https://github.com/ava-labs/avalanche-docs/blob/master/docs/nodes/maintain/avalanchego-config-flags.md

Sure thing there it is: https://github.com/ava-labs/avalanche-docs/pull/1441
