### ISSUE TITLE
Exploded View of Table of Contents

### ISSUE THREAD

**Issue by richardpringle** [ava-labs/avalanche-docs#1444]
As a developer, sometimes you know what you want to do, but you don't know the proper terms to describe it, which makes it difficult to search for a tutorial. It would be so nice to be able to see *all of the content* by heading and sub-heading to be able to navigate to what *might be* the page you're looking for. You still might have to visit a couple of pages before you find exactly what you want, but being able to see sub-headings without actually visiting a page can be a good indicator if you're looking in the right place or not. 

A perfect example of seeing all the headings and sub-headings is ["the plan"](https://app.mural.co/t/personal7645/m/personal7645/1686083088008/92027b759f40faab310a203319c46fa04b7b404a?sender=u7d940a27a826fdb242ac6662)

**Comment by meaghanfitzgerald** [comment]
@richardpringle do you know of any example implementations i could reference so that we don't have to build from scratch?

**Comment by laviniat1996** [comment]
@meaghanfitzgerald is this still relevant?
