### ISSUE TITLE
Missing transaction types in the list

### ISSUE THREAD

**Issue by kanatliemre** [ava-labs/avalanche-docs#1463]
**Describe the bug**

We are missing some of the latest tx types in this description, mainly subnet transaction. 

https://docs.avax.network/specs/platform-transaction-serialization#unsigned-transactions

**Comment by meaghanfitzgerald** [comment]
Where are the latest tx types listed? where can this information be found

**Comment by meaghanfitzgerald** [comment]
At the bottom of the page you linked, you can hit 

![Image](https://github.com/ava-labs/avalanche-docs/assets/99047250/3ed9dfac-ecdc-443b-938e-f2168750a0d9)

to edit the file and directly raise a PR without having to clone the repo. Please raise a PR when you get the chance.
