### ISSUE TITLE
Multilingual support on Avalanche Docs

### ISSUE THREAD

**Issue by anuragasawa20** [ava-labs/avalanche-docs#1539]
Current Status
The documentation website includes only a dropdown to select language but our only supported language is English. This is causing confusion, preventing us from supporting devs from our target markets/regions. It is stopping the userBase of Avalanche because of not having a support for Non-english Native regions.

Expected Behavior
We should add multiple other Languages. This will improve the user experience and ensure that the documentation is clear and reached a wider developer audience.

Steps to Reproduce
Visit the documentation website.
Observe the presence of the language selection dropdown in the navbar.

Proposed Solution
Apply the translate library to the docs so it can be translated in multiple other languages. It can be done by i18n. I have been done it for push protocol (https://push.org/) and got bounty. I will do this thing in just 3-4 Days.  
Alternative: We've been working on a solution to translate support and dev docs into Hindi and Japanese, Spanish and more other languages. Here is the proposal and cost to translate the entire dev docs to more multiple languages.

Crowdin:

-requires manual hiring of translators
-also had issues w/past translations due to crypto-specific terms
-Requires more hands-on updates for each sync/update, including a PR for each update on Dev docs

We can bring over the translated library called i18n and it also help reduce the costs as some words can be translated easily. So let's
have a conversation about this

**Comment by meaghanfitzgerald** [comment]
https://github.com/ava-labs/avalanche-docs/issues/1383

**Comment by meaghanfitzgerald** [comment]
There is an identical issue open, please move the conversation there. Thank you
