### ISSUE TITLE
Use exact versioning in package.json

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/avalanche-docs#1592]
**Describe the bug**
Exact versions should be used in package.json to avoid potential bugs by not-exact version upgrade of dependencies.

**Comment by laviniat1996** [comment]
Hi @yulin-dong , can you provide an example for exact versioning?

**Comment by yulin-dong** [comment]
https://github.com/ava-labs/avalanchejs/blob/master/package.json uses exact version, instead of ^

**Comment by laviniat1996** [comment]
@yulin-dong Sorry for the delay. I'll look into it this week.

**Comment by laviniat1996** [comment]
Thank you @meaghanfitzgerald
