### ISSUE TITLE
Postman Tutorial - environment import

### ISSUE THREAD

**Issue by QuuxFooBaz** [ava-labs/avalanche-docs#170]
The URL in the tutorial does not work.  It is:

https://raw.githubusercontent.com/ava-labs/avalanche-postman-collection/master/Example_Avalanche_Environment.postman_environment.json

and should be: 

https://raw.githubusercontent.com/ava-labs/avalanche-postman-collection/master/Example-Avalanche-Environment.postman_environment.json

**Comment by danlaine** [comment]
Thanks, fixed [here](https://github.com/ava-labs/avalanche-docs/commit/d625bba8759ca21b781fd64b4e25dcffab75eaca)
