### ISSUE TITLE
The method debug_traceTransaction does not exist/is not available

### ISSUE THREAD

**Issue by HelmiTrabelsi** [ava-labs/avalanche-docs#1733]
**Describe the bug**
I have a running subnet, and I connected a block explorer to one of the RPC nodes. Starting the block explorer, this error started popping up in the node logs:

```
INFO [04-09|13:09:14.172] <23SUgLgnzQcai7ceCSnKcWQieQrfSVG4Mk5tof8Tp Chain> github.com/ava-labs/subnet-evm/rpc/handler.go:576: Served debug_traceTransaction reqid=0  execTime="8.193µs"   procTime="11.607µs"   totalTime="11.906µs"   err="the method debug_traceTransaction does not exist/is not available"
```
I added the debug tracer to the node config file, but I'm still getting the same error. Here is my config file:

```
{
    "skip-upgrade-check": true,
    "api-admin-enabled": true,
    "eth-apis": [
      "eth",
      "eth-filter",
      "net",
      "web3",
      "internal-eth",
      "internal-blockchain",
      "internal-transaction",
      "debug-tracer",
    ],
    "pruning-enabled": false,
    "http-host": "",
    "http-port":,
    "network-id": "fuji",
    "public-ip": "",
    "staking-port": ,
    "state-sync-enabled": true,
    "track-subnets": "urbPP4Cw3JQfM3cd9i95ayVo6st8b2VeqaY"
}
```

**Expected behavior**
How can I enable debug tracer on a private subnet?

**Configuration:**
- OS: ubuntu
- Version avalanchego/1.11.3

**Comment by PinkFromTheFuture** [comment]
Adding more data to the issue, we're looking to enable the debut tracer on the Chain, not the subnet.

Here is an example. When running:

 ```
curl http://127.0.0.1:9123/ext/bc/23SUgLgnzQcai7ceCSnKcWQieQwkUsUpM8HrfSVG4Mk5tof8Tp/rpc \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"debug_traceTransaction","params":["0x154bbe502added59dd0dfc4198fe584a85abdfcc7a0c842aa43b9b75cb62b154", {}],"id":1,"jsonrpc":"2.0"}'
```

outputs, on any node (all of them have debug-tracer on the config):
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32601,"message":"the method debug_traceTransaction does not exist/is not available"}}
```

**Comment by PinkFromTheFuture** [comment]
We opened issues on the more pertinent repos:

https://github.com/ava-labs/avalanchego/issues/2939
https://github.com/ava-labs/subnet-evm/issues/1147

This one here can be closed.
