### ISSUE TITLE
Remove Elastic Subnets docs

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/avalanche-docs#1805]
# Deprecation of Elastic Subnets 

Cli has [deprecated Elastic Subnets.](https://github.com/ava-labs/avalanche-cli/pull/2068) This should be removed from the docs prior to the next network upgrade. 

[TransformSubnetTx](https://github.com/ava-labs/avalanchego/pull/3152) is being deprecated with Etna.

This should be done after https://github.com/ava-labs/avalanche-docs/issues/1807.

**Comment by ashucoder9** [comment]
@owenwahlgren https://github.com/ava-labs/avalanche-docs/pull/1801
