### ISSUE TITLE
Fix bad links in docs

### ISSUE THREAD

**Issue by owenwahlgren** [ava-labs/avalanche-docs#1886]
Wrap up fixing bad links inside the docs.
Should be done after https://github.com/ava-labs/avalanche-docs/pull/1885

**Comment by meaghanfitzgerald** [comment]
`https://docs.avax.network/nodes/run/using-install-script/installing-avalanche-go` should link to [Install Script] on [this page](https://docs.avax.network/nodes/configure/configs-flags#config-file)
