### ISSUE TITLE
Replace Subnet Images

### ISSUE THREAD

**Issue by owenwahlgren** [ava-labs/avalanche-docs#1919]
This image is not accurate post-etna:
https://docs.avax.network/learn/avalanche-l1s

Replace with accurate image from https://docs.google.com/presentation/d/1XVtutHGbrlgtbgYw_gs1gdI5iAzeLXNL3TV6vv-hVaE/edit#slide=id.g2e0ae9feae8_0_0

Find other images that may be misleading and replace

**Comment by martineckardt** [comment]
https://docs.google.com/presentation/d/1XVtutHGbrlgtbgYw_gs1gdI5iAzeLXNL3TV6vv-hVaE/edit#slide=id.g2e0ae9feae8_0_0
