### ISSUE TITLE
Reorg L1 docs

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/avalanche-docs#1928]
Split

- [x] Split VM section: EVM L1s & Custom VM L1s
- [x] Everything Precompile / EVM related from Avalanche L1s => EVM L1s
- [x] Remove Elastic L1s
- [x] Add Validator Manager Docs to EVM L1s => Customizations

**Comment by meaghanfitzgerald** [comment]
just need https://github.com/ava-labs/avalanche-docs/pull/1918 merged and then we can close this issue

**Comment by meaghanfitzgerald** [comment]
https://github.com/ava-labs/avalanche-docs/pull/1918 was merged
