### ISSUE TITLE
Update P-Chain API page

### ISSUE THREAD

**Issue by owenwahlgren** [ava-labs/avalanche-docs#1954]
Update https://docs.avax.network/api-reference/p-chain/api to include support for the following methods:
```
Added info.upgrades
Added platform.getFeeConfig
Added platform.getFeeState
Added platform.getL1Validator
Added platform.getProposedHeight
Added platform.getValidatorsAt
```

details here:
https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/service.md

**Comment by meaghanfitzgerald** [comment]
this is covered by https://github.com/ava-labs/avalanche-docs/issues/1952
