### ISSUE TITLE
Update Create a new Blockchain docs.

### ISSUE THREAD

**Issue by cgcardona** [ava-labs/avalanche-docs#23]
In our [create a new blockchain tutorial](https://docs.avax.network/build/tutorials/platform/create-a-new-blockchain) it's not clear that your validator must be validating the default subnet before creating your own subnet and adding a validator and blockchain.

Make the docs more clear when there are implicit and understood steps happening. Link out to the tutorials that cover those core and understood steps just so people who don't know the platform as well as us don't get tripped up on something which we consider super basic and obvious.

**Comment by jpop32** [comment]
Updated the tutorial with a new section at the top with necessary prerequisites, with links sprinkled throughout. Also corrected some stale links in the rest of the tutorial and made them all relative where possible. #27

**Comment by lorrp1** [comment]
@cgcardona how are fee paid in the subnet between transactions?
