### ISSUE TITLE
Syntax of `--http-host` parameter for avalanchego is unclear in the docs

### ISSUE THREAD

**Issue by ssg** [ava-labs/avalanche-docs#325]
(I'm not sure if this is the right repository for this, because I couldn't find the relevant documentation here but here it goes)

The syntax of `--http-host` command-line parameter for avalanchego is unclear in the docs: https://docs.avax.network/build/references/command-line-interface

- Does it accept only IP addresses, or does it accept hostnames too? (I looked at the golang docs https://pkg.go.dev/net it looks like it accepts hostnames too)
- Is it possible to provide multiple http-host parameters to make avalanchego listen on multiple IP addresses like by repeating `--http-host` or comma separating hosts etc? (Doesn't seem possible)

I would've sent a PR request if I could find the docs.

**Comment by 0fatih** [comment]
I think it is also accept hostnames too. When I tried to run with `facebook.com`, it says 

`FATAL[09-20|17:22:35] node/node.go#374: API server dispatch failed with listen tcp 157.240.234.35:9650: bind: cannot assign requested address`

I'll create a PR for this. Thank you for your attention!
