### ISSUE TITLE
Avalanche-installer.sh no longer able to find latest version of avalanchego to download

### ISSUE THREAD

**Issue by bryanwb** [ava-labs/avalanche-docs#434]
Environment: Ubuntu 20.04

Since this commit, the installer can no longer find the latest version of avalanchego to install

https://github.com/ava-labs/avalanche-docs/commit/d10247aba9701187f6b7e0bb115770c2f08379f6

**Comment by dhrubabasu** [comment]
Fixed in e4b922fd83acae6952510ef52c21ef64bd84b1cc, thank you!
