### ISSUE TITLE
Request : How to prepare / schedule a mandatory upgrade on a subnet EVM chain

### ISSUE THREAD

**Issue by executionreverted** [ava-labs/avalanche-docs#594]
This is a doc request.

When state transition function needs to change, how to prepare / schedule a mandatory upgrade on an EVM based chain to avoid backend error and mismatch of block hashes

**Comment by aaronbuchwald** [comment]
Added a feature to enable easy upgrades documented here: https://docs.avax.network/subnets/customize-a-subnet#network-upgrades-enabledisable-precompiles.
