### ISSUE TITLE
AvalancheGo documentation: config and flags: Logging

### ISSUE THREAD

**Issue by neuhaus** [ava-labs/avalanche-docs#653]
The documentation about logging at https://docs.avax.network/build/references/avalanchego-config-flags disagrees with the help given by running "avalanchego --help".

The loglevel "trace" is missing.
Also according to "--help" the loglevel defaults to "debug", not "Info".

**Comment by ceyonur** [comment]
AvalancheGo log-level is defined here: https://docs.avax.network/build/references/avalanchego-config-flags/#logging. The link you're referring is for C-chain (coreth) log levels, which are different than AvalancheGo log-levels. 

You still have point though. C-chain log level should be updated to `info` and `--log-display-level` helper text in AvalancheGo is missing `trace` level. Fixing helper text in AvalancheGo as well, thanks!
