### ISSUE TITLE
how to get c chain address private key in local test network is not mentioned in document

### ISSUE THREAD

**Issue by huahuayu** [ava-labs/avalanche-docs#661]
Hi guys, the last paragraph in this document mentioned how to get avax, but it's in x-chain

https://github.com/ava-labs/avalanche-docs/blob/master/docs/build/tutorials/platform/create-a-local-test-network.md

now the x-chain's private key is known, the question is how to convert x-chain private key to c chain private key, so I can control and send fund in c chain address to c chain address via metamask?

**Comment by huahuayu** [comment]
@yulin-dong could you help to clarify?

**Comment by ceyonur** [comment]
It's a conversion from CB58 to Hex (without `PrivateKey-` part). 
We have this tooling : https://avatools.io/. If you want to keep it local (and you should) you can go offline on that page and convert then close the page before going online again.

Or you can use AvalancheJS https://github.com/ava-labs/avalanchejs for that. example code snippet: https://gist.github.com/cgcardona/b0c08f7975679fb43e015daf2ab7cc72
