### ISSUE TITLE
Grafana dashboard Fuji network

### ISSUE THREAD

**Issue by piccadil** [ava-labs/avalanche-docs#816]
I've deployed an avalanche node on the Fuji network, and imported dashboard from https://github.com/ava-labs/avalanche-docs/tree/master/dashboards , but some panels are not working. I looked at the metrics, and didn't find a `avalanche_C_blks_accepted_count` for example. The same issue for many other metrics.

**Comment by jpop32** [comment]
Is the bootstrapping of the node finished? Until it is (which can take a long time), many of the metrics won't be available.

**Comment by piccadil** [comment]
Yes, the node wasn't bootstraped, after bootstraping all metrics are available. Thank a lot.

**Comment by jpop32** [comment]
Cool, glad it turned out ok.
