### ISSUE TITLE
Update Network Protocol Spec

### ISSUE THREAD

**Issue by StephenButtolph** [ava-labs/avalanche-docs#992]
The existing spec is quite out of date... For example it references a few messages that no longer exist:

- GetVersion
- GetPeers

It also seems to be missing... A few messages...

- Pong
- Ping
- GetAcceptedFrontier
- AcceptedFrontier
- GetAccepted
- Accepted
- GetAncestors
- Ancestors
- AppRequest
- AppResponse
- AppGossip
- GetStateSummaryFrontier
- StateSummaryFrontier
- GetAcceptedStateSummary
- AcceptedStateSummary

It also seems to use `SubnetID` where it should be using `ChainID`

**Comment by meaghanfitzgerald** [comment]
lol
